/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workshop6.GUI;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import workshop6.DBClasses.PackageDB;
import workshop6.utils.Validator;
import workshop6.Entity.Package;

/**
 *
 *
 */
public class AddEditPackagesFrame extends javax.swing.JInternalFrame {

    public static boolean addPackages;
    public workshop6.Entity.Package pkg;
    PackageMainFrame main;
    //public Package modPkg;
    
    /**
     * Creates new form AddEditPackagesFrame
     */
    public AddEditPackagesFrame(PackageMainFrame m, boolean addpackages, workshop6.Entity.Package pkg) {
        initComponents();
        this.addPackages = addpackages;
        this.pkg = pkg;
        main = m;
        if(addPackages)
        {
            this.setTitle("Add Package");
            btnEditProductSuppliers.setEnabled(false);
        }
        else
        {
            this.setTitle("Modify Package");
            lblAddEditPackages.setText("Currently editing Package ID: " + pkg.getPackageId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtAddEditPkgName = new javax.swing.JTextField();
        txtAddEditPkgBasePrice = new javax.swing.JTextField();
        txtAddEditPkgAgencyCommission = new javax.swing.JTextField();
        txtAddEditPkgDescription = new javax.swing.JTextField();
        btnSavePackage = new javax.swing.JButton();
        btnExitPackages = new javax.swing.JButton();
        lblAddEditPackages = new javax.swing.JLabel();
        cmbAddEditPkgStartDate = new com.toedter.calendar.JDateChooser();
        cmbAddEditPkgEndDate = new com.toedter.calendar.JDateChooser();
        btnEditProductSuppliers = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel11.setText("Package Name");

        jLabel12.setText("Package Base Price");

        jLabel13.setText("Package Start Date");

        jLabel15.setText("Package End Date");

        jLabel16.setText("Package Agency Commission");

        jLabel17.setText("Package Description");

        txtAddEditPkgName.setName("Package Name"); // NOI18N

        txtAddEditPkgBasePrice.setName("Package Base Price"); // NOI18N

        txtAddEditPkgAgencyCommission.setName("Package Agency Commission"); // NOI18N

        txtAddEditPkgDescription.setName("Package Description"); // NOI18N

        btnSavePackage.setText("Save");
        btnSavePackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePackageActionPerformed(evt);
            }
        });

        btnExitPackages.setText("Exit");
        btnExitPackages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitPackagesActionPerformed(evt);
            }
        });

        lblAddEditPackages.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAddEditPackages.setText("Add Package");

        cmbAddEditPkgStartDate.getDateEditor().setEnabled(false);
        cmbAddEditPkgStartDate.setDateFormatString("yyyy-MM-dd");
        cmbAddEditPkgStartDate.setName("Package Start Date"); // NOI18N

        cmbAddEditPkgEndDate.getDateEditor().setEnabled(false);
        cmbAddEditPkgEndDate.setDateFormatString("yyyy-MM-dd");
        cmbAddEditPkgEndDate.setName("Package End Date"); // NOI18N

        btnEditProductSuppliers.setText("Edit Products and Suppliers");
        btnEditProductSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductSuppliersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSavePackage)
                        .addGap(61, 61, 61)
                        .addComponent(btnExitPackages)
                        .addGap(64, 64, 64)
                        .addComponent(btnEditProductSuppliers)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddEditPkgBasePrice)
                            .addComponent(txtAddEditPkgAgencyCommission))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel11))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtAddEditPkgName)
                                .addGap(34, 34, 34))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbAddEditPkgStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbAddEditPkgEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAddEditPkgDescription))
                                .addContainerGap())))
                    .addComponent(lblAddEditPackages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblAddEditPackages, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtAddEditPkgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAddEditPkgDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(cmbAddEditPkgStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbAddEditPkgEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddEditPkgBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAddEditPkgAgencyCommission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSavePackage)
                    .addComponent(btnExitPackages)
                    .addComponent(btnEditProductSuppliers))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePackageActionPerformed
        if(AllFieldsValid()) //Adam- added the validation here.
        {
            if(addPackages)
            {
                pkg = new Package();
                pkg = putPackageData(pkg);
                boolean addPackage = PackageDB.addPackage(pkg);
                pkg = PackageDB.getPackage(PackageDB.getPackageIDs().lastElement());
                main.pkg = pkg;
                if(addPackage)
                {
                    PackageMainFrame.UpdatePackagesList();
                    JOptionPane.showMessageDialog(null, "Package added successfully. You can now add products and suppliers.");
                    btnEditProductSuppliers.setEnabled(true);
                }
                
                
                //main.postData(pkg);
                //this.setVisible(false);

            }
            else
            {
                Package modPkg = new Package();
                modPkg.setPackageId(pkg.getPackageId());
                modPkg = getModifiedPackageData(modPkg);
                boolean modPackageStatus = PackageDB.updatePackage(modPkg);
                if(modPackageStatus)
                JOptionPane.showMessageDialog(null, "Package modified successfully");
                main.modPkg = modPkg;
                PackageMainFrame.UpdatePackagesList();
                // main.postData(modPkg);
                //this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnSavePackageActionPerformed

    private void btnExitPackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitPackagesActionPerformed
        //main.initPackageIdCombo();
        this.dispose();
        //System.exit(0);
    }//GEN-LAST:event_btnExitPackagesActionPerformed

    private void btnEditProductSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductSuppliersActionPerformed
        if(pkg != null)
        {
            if(!Main.checkIfFrameAlreadyOpen(EditSupplierProductFrame.class))
            {  
                EditSupplierProductFrame editSupplierProduct = new EditSupplierProductFrame(pkg);
                getDesktopPane().add(editSupplierProduct);
                editSupplierProduct.setVisible(true);
                try {
                    editSupplierProduct.setSelected(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(AgentMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "You are currenly already editng Product/Supplier informatino from a package. Please close this window to open a new editor");
            }
           // EditSupplierProduct editSupplierProduct = new EditSupplierProduct(this, true, pkg);
           // editSupplierProduct.setVisible(true);
        }
    }//GEN-LAST:event_btnEditProductSuppliersActionPerformed

    //Geetha - Method to get the modified package details
     public workshop6.Entity.Package getModifiedPackageData(workshop6.Entity.Package modPkg)
    {      
        modPkg.setPkgName(txtAddEditPkgName.getText());
        modPkg.setPkgDesc(txtAddEditPkgDescription.getText());
        modPkg.setPkgStartDate(cmbAddEditPkgStartDate.getDate());
        modPkg.setPkgEndDate(cmbAddEditPkgEndDate.getDate());
        modPkg.setPkgBasePrice(Double.parseDouble(txtAddEditPkgBasePrice.getText()));
        modPkg.setPkgAgencyCommission(Double.parseDouble(txtAddEditPkgAgencyCommission.getText()));
       return modPkg;
    }
      //Geetha - Method to get the values from text field and put it in package bean
    public workshop6.Entity.Package putPackageData(workshop6.Entity.Package pkg)
    {
        pkg.setPkgName(txtAddEditPkgName.getText());
        pkg.setPkgDesc(txtAddEditPkgDescription.getText());
        pkg.setPkgStartDate(cmbAddEditPkgStartDate.getDate());
        pkg.setPkgEndDate(cmbAddEditPkgEndDate.getDate());
        pkg.setPkgBasePrice(Double.parseDouble(txtAddEditPkgBasePrice.getText()));
        pkg.setPkgAgencyCommission(Double.parseDouble(txtAddEditPkgAgencyCommission.getText()));
        return pkg;
    }
    
     //Geetha - Method to display package details in text fields
    public void displayPackage(Package pkg) {
        //SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        //NumberFormat currency = NumberFormat.getCurrencyInstance();
        //currency.setMinimumFractionDigits(2);
        //DecimalFormat df = new DecimalFormat("###.##");
        txtAddEditPkgName.setText(pkg.getPkgName());
        txtAddEditPkgDescription.setText(pkg.getPkgDesc());
        cmbAddEditPkgStartDate.setDate(pkg.getPkgStartDate());
        cmbAddEditPkgEndDate.setDate(pkg.getPkgEndDate());
        txtAddEditPkgBasePrice.setText(String.valueOf(String.format("%.2f",pkg.getPkgBasePrice())));
        txtAddEditPkgAgencyCommission.setText(String.valueOf(String.format("%.2f",pkg.getPkgAgencyCommission())));
        //txtAddEditPkgBasePrice.setText(currency.format(pkg.getPkgBasePrice()));
        //txtAddEditPkgAgencyCommission.setText(currency.format(pkg.getPkgAgencyCommission()));
    }
    
    //Adam - Function to check that the package end date is after the package start date
    private boolean checkDatesValid()
    {        
        if(cmbAddEditPkgStartDate.getDate().compareTo(cmbAddEditPkgEndDate.getDate()) > 0)
        {
            JOptionPane.showMessageDialog(this, "The package end date cannot be before the package start date.");
            return false;
        }
        else
            return true;
    }
    
    //Adam- function to check that the package commission is smaller than or equal to the package base price.
    private boolean checkCommisionValid()
    {
        if(Double.parseDouble(txtAddEditPkgAgencyCommission.getText()) > Double.parseDouble(txtAddEditPkgBasePrice.getText()))
        {
            JOptionPane.showMessageDialog(this, "The package commission rate cannot be more than the package base price");
            return false;
        }
        else return true;
    }
    
    //Adam - Function to check that all the entered values are valid to be to properly inputted into the database
    private boolean AllFieldsValid()
    {
        return Validator.hasTextOrIsSelected(txtAddEditPkgName) 
            && Validator.hasTextOrIsSelected(txtAddEditPkgDescription)             
            && Validator.hasTextOrIsSelected(cmbAddEditPkgStartDate)              
            && Validator.hasTextOrIsSelected(cmbAddEditPkgEndDate)
                
            && Validator.hasTextOrIsSelected(txtAddEditPkgBasePrice)
            && Validator.isDouble(txtAddEditPkgBasePrice)
                
            && Validator.hasTextOrIsSelected(txtAddEditPkgAgencyCommission)
            && Validator.isDouble(txtAddEditPkgAgencyCommission)
                
            && checkDatesValid() 
            && checkCommisionValid(); //Do not change the location of this checkCommissionValid method call.
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditProductSuppliers;
    private javax.swing.JButton btnExitPackages;
    private javax.swing.JButton btnSavePackage;
    private com.toedter.calendar.JDateChooser cmbAddEditPkgEndDate;
    private com.toedter.calendar.JDateChooser cmbAddEditPkgStartDate;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAddEditPackages;
    private javax.swing.JTextField txtAddEditPkgAgencyCommission;
    private javax.swing.JTextField txtAddEditPkgBasePrice;
    private javax.swing.JTextField txtAddEditPkgDescription;
    private javax.swing.JTextField txtAddEditPkgName;
    // End of variables declaration//GEN-END:variables
}
