/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workshop6.GUI;

import java.beans.PropertyVetoException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import workshop6.DBClasses.AgentDB;
import workshop6.DBClasses.CustomerDB;
import workshop6.Entity.Agent;
import workshop6.Entity.Customer;

/**
 *All code not done by Darya was done by Max 
 * 
 */
public class AgentMainFrame extends javax.swing.JInternalFrame {
    public Agent agt;
    private static ComboBoxModel cbAgentIdModel;
    
    /**
     * Creates new form AgentMainFrame
     */
    public AgentMainFrame() {
        initComponents();
        UpdateAgentsList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        agentFieldPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cmbAgentId = new javax.swing.JComboBox();
        txtAgencyId = new javax.swing.JTextField();
        txtAgentBusPhone = new javax.swing.JTextField();
        txtAgentFirstName = new javax.swing.JTextField();
        txtAgentLastName = new javax.swing.JTextField();
        txtAgentMiddleInitial = new javax.swing.JTextField();
        txtAgentPosition = new javax.swing.JTextField();
        rbActive = new javax.swing.JRadioButton();
        rbInactive = new javax.swing.JRadioButton();
        txtAgentEmail = new javax.swing.JTextField();
        btnEditAgent = new javax.swing.JButton();
        btnAddAgent = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Agent Maintain Form");
        setToolTipText("");
        setName(""); // NOI18N

        agentFieldPanel.setLayout(new java.awt.GridBagLayout());

        jLabel14.setText("Agent ID");
        jLabel14.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(jLabel14, gridBagConstraints);

        jLabel18.setText("Agency ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(jLabel18, gridBagConstraints);

        jLabel19.setText("Agent Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(jLabel19, gridBagConstraints);

        jLabel20.setText("Agent Business Phone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(jLabel20, gridBagConstraints);

        jLabel21.setText("Agent First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(jLabel21, gridBagConstraints);

        jLabel22.setText("Agent Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(jLabel22, gridBagConstraints);

        jLabel23.setText("Agent Middle Initial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(jLabel23, gridBagConstraints);

        jLabel24.setText("Agent Position");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(jLabel24, gridBagConstraints);

        jLabel25.setText("Agent Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(jLabel25, gridBagConstraints);

        cmbAgentId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAgentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgentIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(cmbAgentId, gridBagConstraints);

        txtAgencyId.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(txtAgencyId, gridBagConstraints);

        txtAgentBusPhone.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(txtAgentBusPhone, gridBagConstraints);

        txtAgentFirstName.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(txtAgentFirstName, gridBagConstraints);

        txtAgentLastName.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(txtAgentLastName, gridBagConstraints);

        txtAgentMiddleInitial.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(txtAgentMiddleInitial, gridBagConstraints);

        txtAgentPosition.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(txtAgentPosition, gridBagConstraints);

        rbActive.setText("Active");
        rbActive.setEnabled(false);
        rbActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActiveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(rbActive, gridBagConstraints);

        rbInactive.setText("Inactive");
        rbInactive.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 1);
        agentFieldPanel.add(rbInactive, gridBagConstraints);

        txtAgentEmail.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        agentFieldPanel.add(txtAgentEmail, gridBagConstraints);

        btnEditAgent.setText("Edit");
        btnEditAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAgentActionPerformed(evt);
            }
        });

        btnAddAgent.setText("Add");
        btnAddAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnAddAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agentFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(agentFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAgent)
                    .addComponent(btnEditAgent))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void UpdateAgentsList()
    {
        cmbAgentId.removeAll();
        cbAgentIdModel = new DefaultComboBoxModel(AgentDB.GetAgentIds());
        cmbAgentId.setModel(cbAgentIdModel);
        cmbAgentId.setSelectedIndex(0);
        
    }
    
    private void cmbAgentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgentIdActionPerformed
        String agentId = (String)cmbAgentId.getSelectedItem();
        agt = AgentDB.GetAgentById(agentId);
        txtAgentFirstName.setText(agt.getAgtFirstName());
        txtAgentMiddleInitial.setText(agt.getAgtMiddleInitial());
        txtAgentLastName.setText(agt.getAgtLastName());
        txtAgentEmail.setText(agt.getAgtEmail());
        txtAgentBusPhone.setText(agt.getAgtBusPhone());
        txtAgentPosition.setText(agt.getAgtPosition());
        txtAgencyId.setText(Integer.toString(agt.getAgencyId()));

        if (agt.isActive() == true)
        {
            rbActive.setSelected(true);
            rbInactive.setSelected(false);
        }
        else
        {
            rbInactive.setSelected(true);
            rbActive.setSelected(false);
        }
        //Darya: chekcing if we have an inactive agent with customers
       /* if (!agt.isActive() == true && agentHasCustomers(Integer.parseInt(agentId)))
        {
            rbInactive.setSelected(true);
            //Darya: if the agents is inactive we need a message to pop up if
            //the agent still has assigned customers
            displayReassignmentDialog(agt.getAgentId());
        }*/
    }//GEN-LAST:event_cmbAgentIdActionPerformed

    
    //Darya: method to check if agent has any customers
    public static boolean agentHasCustomers(int agentId)
    {
        Vector<Customer> customers = new Vector<Customer>();
        customers = CustomerDB.GetCustomersByAgentId(agentId);
        if(!customers.isEmpty())
            return true;
        else
            return false;
    }
    
     //Darya: this method is work in progress
    private static void displayReassignmentDialog(int agentId){
        
            int response = JOptionPane.showConfirmDialog(null, "Would you like to reassign agent's customers?", "Agent is Inactive",
	    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
	    if (response == JOptionPane.NO_OPTION) {
	      //System.out.println("No button clicked");
                //close dialog window
	    } else if (response == JOptionPane.YES_OPTION) {
	      System.out.println("Yes button clicked");
              //open the ReassignCustomers form and pass in the agentId parameter
              new ReassignCustomersForm(agentId).setVisible(true);
              
	    } else if (response == JOptionPane.CLOSED_OPTION) {
	      //System.out.println("JOptionPane closed");
	    }
    }
    
    private void rbActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbActiveActionPerformed

    private void btnEditAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAgentActionPerformed
        //System.out.println(AgentDB.GetAgentById(cmbAgentId.getSelectedItem().toString()));
        
        if(!Main.checkIfFrameAlreadyOpen(AddEditAgentsFrame.class))
        {  
                     
            AddEditAgentsFrame.addEditAgent = false;
            AddEditAgentsFrame addEditAgentForm = new AddEditAgentsFrame();  
           
            //addEditAgentForm.setVisible(true);
            //PackageMainFrame frame = new PackageMainFrame();
            getDesktopPane().add(addEditAgentForm);
            addEditAgentForm.setVisible(true);
            try {
                addEditAgentForm.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AgentMainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "You are currently "+ ((AddEditAgentsFrame.addEditAgent == false) ? "editing" : "adding") +" an agent. Please close this window in order to open a new editor.");
        }

    }//GEN-LAST:event_btnEditAgentActionPerformed

    private void btnAddAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAgentActionPerformed

        if(!Main.checkIfFrameAlreadyOpen(AddEditAgentsFrame.class))
        {  
            AddEditAgentsFrame.addEditAgent = true;
            AddEditAgentsFrame addEditAgentForm = new AddEditAgentsFrame();  
           
            //addEditAgentForm.setVisible(true);
            //PackageMainFrame frame = new PackageMainFrame();
            getDesktopPane().add(addEditAgentForm);
            addEditAgentForm.setVisible(true);
            try {
                addEditAgentForm.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(AgentMainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "You are currently "+ ((AddEditAgentsFrame.addEditAgent == false) ? "editing" : "adding") +" an agent. Please close this window in order to open a new editor.");
        }
        
    }//GEN-LAST:event_btnAddAgentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agentFieldPanel;
    private javax.swing.JButton btnAddAgent;
    private javax.swing.JButton btnEditAgent;
    public static javax.swing.JComboBox cmbAgentId;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JRadioButton rbActive;
    private javax.swing.JRadioButton rbInactive;
    private javax.swing.JTextField txtAgencyId;
    private javax.swing.JTextField txtAgentBusPhone;
    private javax.swing.JTextField txtAgentEmail;
    private javax.swing.JTextField txtAgentFirstName;
    private javax.swing.JTextField txtAgentLastName;
    private javax.swing.JTextField txtAgentMiddleInitial;
    private javax.swing.JTextField txtAgentPosition;
    // End of variables declaration//GEN-END:variables
}
