/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package workshop6.GUI;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import workshop6.DBClasses.PackagesProductsSuppliersDB;
import workshop6.DBClasses.ProductDB;
import workshop6.DBClasses.ProductSupplierDB;
import workshop6.DBClasses.SupplierDB;
import workshop6.Entity.Product;
import workshop6.Entity.ProductSupplier;
import workshop6.Entity.Supplier;

/**
 *
 * @author Adam
 */
public class EditSupplierProduct extends javax.swing.JDialog {
    
    //the model that will be used to populate the PtroductsSuppliers Table
    private DefaultTableModel tablemodel;
    //The package we are currently working with
    private workshop6.Entity.Package pkg;
    //The models that will be used for products and suppliers combo boxes
    private DefaultComboBoxModel productsModel, supplierModel;
    /**
     * Creates new form EditSupplierProduct
     */
    public EditSupplierProduct(java.awt.Frame parent, boolean modal, workshop6.Entity.Package pkg) {
        super(parent, modal);
        initComponents();
        //set the local vars
        this.pkg = pkg;    
        tablemodel = (DefaultTableModel)tblProductsSuppliers.getModel();
        
        //Get the list of productsuppliers that are related to the package we are working with
        List<ProductSupplier> productsSuppliers = ProductSupplierDB.getProductSuppliersForPackage(pkg.getPackageId());
        //If the productsuppliers list is empty, disable the delete button
        if(productsSuppliers.isEmpty())
            btnRemoveProductSupplier.setEnabled(false);
        
        //Loop through the list of productsuppliers and it to the table model
        for(ProductSupplier productSupplier : productsSuppliers)
        {
            String prodName = ProductDB.getProductById(productSupplier.getProductId()).getProdName();
            String suppName = SupplierDB.getSupplierById(productSupplier.getSupplierId()).getSupName();
                
            tablemodel.addRow(new Object[]{productSupplier.getProductSupplierId(), prodName, suppName});
        }
        
        //Assign the model to the table
        tblProductsSuppliers.setModel(tablemodel);
        
        //Populate the products combo box model with the list of products
        productsModel = (DefaultComboBoxModel) cmbProducts.getModel();
        List<Product> products = ProductDB.getAllProducts();
        for(Product product : products)
        {
            //cmbProducts.addItem(product.getProdName());
            productsModel.addElement(product);
                  
        }
        //Assign the model to the combo box
        cmbProducts.setModel(productsModel);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductsSuppliers = new javax.swing.JTable();
        btnRemoveProductSupplier = new javax.swing.JButton();
        cmbProducts = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbSuppliers = new javax.swing.JComboBox();
        btmAddProductSupplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblProductsSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product", "Supplier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductsSuppliers);

        btnRemoveProductSupplier.setText("Remove Product Supplier");
        btnRemoveProductSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductSupplierActionPerformed(evt);
            }
        });

        cmbProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductsActionPerformed(evt);
            }
        });

        jLabel1.setText("Products:");

        jLabel2.setText("Suppliers:");

        btmAddProductSupplier.setText("Add Product and Supplier");
        btmAddProductSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAddProductSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnRemoveProductSupplier))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbSuppliers, 0, 191, Short.MAX_VALUE)
                                    .addComponent(cmbProducts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btmAddProductSupplier)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRemoveProductSupplier)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btmAddProductSupplier)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Function that runs when the user clicks the remove products supplier button
    private void btnRemoveProductSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductSupplierActionPerformed
        //Make sure we have actaully selected a row in the table
        if(tblProductsSuppliers.getSelectedRow() != -1)
        {
            //Attempt to delete the values form the database and update the table
            if(PackagesProductsSuppliersDB.deletePackagesProductsSuppliers(pkg.getPackageId(), (int)tablemodel.getValueAt(tblProductsSuppliers.getSelectedRow(), 0)) != -1)
            {            
                tablemodel.removeRow(tblProductsSuppliers.getSelectedRow());
                JOptionPane.showMessageDialog(null, "The Product and Supplier has been deleted.");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error deleting ");
            }
        }
        else //User did not select a row
        {
            JOptionPane.showMessageDialog(null, "You must select a row you wish you remove first");
        }
    }//GEN-LAST:event_btnRemoveProductSupplierActionPerformed
    
    //Function that runs when the user makes a selection in the products combo box
    private void cmbProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductsActionPerformed
        //Clear the suppliers combo box
        cmbSuppliers.removeAllItems();
        
        //Fetch suppliers that are related to this product and populate the suppliers combo box
        supplierModel = (DefaultComboBoxModel) cmbSuppliers.getModel();      
        List<Supplier> suppliers = ProductSupplierDB.getSuppliersForProduct(((Product)productsModel.getSelectedItem()).getProductId());
        for(Supplier supplier : suppliers)
        {
            supplierModel.addElement(supplier);
            //cmbSuppliers.addItem(supplier.getSupName());
        }
        cmbSuppliers.setModel(supplierModel);
    }//GEN-LAST:event_cmbProductsActionPerformed

    //Function that runs when the user clicks the add productsupplier button
    private void btmAddProductSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAddProductSupplierActionPerformed
        //Get the productsupplier obejct based on the product and supplier selection
        ProductSupplier productSupplier = ProductSupplierDB.getProductSupplierFromProductIdAndSupplierId(((Product)productsModel.getSelectedItem()).getProductId(), ((Supplier)(supplierModel.getSelectedItem())).getSupplierId());
        if(productSupplier != null)
        {          
            String prodName = ProductDB.getProductById(productSupplier.getProductId()).getProdName();
            String suppName = SupplierDB.getSupplierById(productSupplier.getSupplierId()).getSupName();
            //Boolean that is used to check if we can add the selected product and supplier to this package
            boolean canAdd = false;    
            for(int i=0; i<tablemodel.getRowCount();i++)
            {
                //If we find the matching productsupplier id in the table. the user cannot add this product supplier as it is already link to this package
                if((int)tablemodel.getValueAt(i, 0) == productSupplier.getProductSupplierId())
                {
                    JOptionPane.showMessageDialog(null, "This package is already linked to this product and supplier.");
                    canAdd = false;
                    break;
                }             
                canAdd = true;             
            }
            if(canAdd)
            {
                if(PackagesProductsSuppliersDB.insertNewPackagesProductsSuppliersEntry(pkg.getPackageId(), productSupplier.getProductSupplierId()) != -1)
                {
                    tablemodel.addRow(new Object[]{productSupplier.getProductSupplierId(), prodName, suppName});
                    JOptionPane.showMessageDialog(null, "Successfully added product and supplier");
                }
                
            }
            //If there is no current productsuppliers linked to this package, we must insert the row
            //you cannot add a row to a empty table model, only insert
            if(tablemodel.getRowCount() == 0)
            {
                if(PackagesProductsSuppliersDB.insertNewPackagesProductsSuppliersEntry(pkg.getPackageId(), productSupplier.getProductSupplierId()) != -1)
                {
                    tablemodel.insertRow(0, new Object[]{productSupplier.getProductSupplierId(), prodName, suppName});
                    JOptionPane.showMessageDialog(null, "Successfully added product and supplier");
                }
            }
        }
        if(tablemodel.getRowCount()!=0)
            btnRemoveProductSupplier.setEnabled(true);
    }//GEN-LAST:event_btmAddProductSupplierActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAddProductSupplier;
    private javax.swing.JButton btnRemoveProductSupplier;
    private javax.swing.JComboBox cmbProducts;
    private javax.swing.JComboBox cmbSuppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductsSuppliers;
    // End of variables declaration//GEN-END:variables
}
