/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package workshop6.GUI;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import workshop6.DBClasses.PackagesProductsSuppliersDB;
import workshop6.DBClasses.ProductDB;
import workshop6.DBClasses.ProductSupplierDB;
import workshop6.DBClasses.SupplierDB;
import workshop6.Entity.Product;
import workshop6.Entity.ProductSupplier;
import workshop6.Entity.Supplier;

/**
 *
 * @author Adam
 */
public class EditSupplierProduct extends javax.swing.JDialog {
    
    DefaultTableModel tablemodel;
    workshop6.Entity.Package pkg;
    DefaultComboBoxModel productsModel, supplierModel;
    /**
     * Creates new form EditSupplierProduct
     */
    public EditSupplierProduct(java.awt.Frame parent, boolean modal, workshop6.Entity.Package pkg) {
        super(parent, modal);
        initComponents();
        this.pkg = pkg;    
        tablemodel = (DefaultTableModel)jTable1.getModel();
            
        List<ProductSupplier> productsSuppliers = ProductSupplierDB.getProductSuppliersForPackage(pkg.getPackageId());
        for(ProductSupplier productSupplier : productsSuppliers)
        {
            String prodName = ProductDB.getProductById(productSupplier.getProductId()).getProdName();
            String suppName = SupplierDB.getSupplierById(productSupplier.getSupplierId()).getSupName();
                
            tablemodel.addRow(new Object[]{productSupplier.getProductSupplierId(), prodName, suppName});
        }
            
        jTable1.setModel(tablemodel);
        
        productsModel = (DefaultComboBoxModel) cmbProducts.getModel();
        List<Product> products = ProductDB.getAllProducts();
        for(Product product : products)
        {
            //cmbProducts.addItem(product.getProdName());
            productsModel.addElement(product);
                  
        }       
        cmbProducts.setModel(productsModel);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRemoveProductSupplier = new javax.swing.JButton();
        cmbProducts = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbSuppliers = new javax.swing.JComboBox();
        btmAddProductSupplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product", "Supplier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnRemoveProductSupplier.setText("Remove Product Supplier");
        btnRemoveProductSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductSupplierActionPerformed(evt);
            }
        });

        cmbProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductsActionPerformed(evt);
            }
        });

        jLabel1.setText("Products:");

        jLabel2.setText("Suppliers:");

        btmAddProductSupplier.setText("Add Product and Supplier");
        btmAddProductSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAddProductSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnRemoveProductSupplier))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbProducts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbSuppliers, 0, 115, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btmAddProductSupplier)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRemoveProductSupplier)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btmAddProductSupplier)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveProductSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductSupplierActionPerformed
        if(jTable1.getSelectedRow() != -1)
        {
            if(PackagesProductsSuppliersDB.deletePackagesProductsSuppliers(pkg.getPackageId(), (int)tablemodel.getValueAt(jTable1.getSelectedRow(), 0)) != -1)
            {
                JOptionPane.showMessageDialog(null, "The Product and Supplier has been deleted.");
                tablemodel.removeRow(jTable1.getSelectedRow());
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error deleting ");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "You must select a row you wish you remove first");
        }
    }//GEN-LAST:event_btnRemoveProductSupplierActionPerformed

    private void cmbProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductsActionPerformed
        cmbSuppliers.removeAllItems();
        supplierModel = (DefaultComboBoxModel) cmbSuppliers.getModel();      
        List<Supplier> suppliers = ProductSupplierDB.getSuppliersForProduct(((Product)productsModel.getSelectedItem()).getProductId());
        for(Supplier supplier : suppliers)
        {
            supplierModel.addElement(supplier);
            //cmbSuppliers.addItem(supplier.getSupName());
        }
        cmbSuppliers.setModel(supplierModel);
    }//GEN-LAST:event_cmbProductsActionPerformed

    private void btmAddProductSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAddProductSupplierActionPerformed
        ProductSupplier productSupplier = ProductSupplierDB.getProductSupplierFromProductIdAndSupplierId(((Product)productsModel.getSelectedItem()).getProductId(), ((Supplier)(supplierModel.getSelectedItem())).getSupplierId());
        if(productSupplier != null)
        {          
            String prodName = ProductDB.getProductById(productSupplier.getProductId()).getProdName();
            String suppName = SupplierDB.getSupplierById(productSupplier.getSupplierId()).getSupName();
            boolean canAdd = false;    
            for(int i=0; i<tablemodel.getRowCount();i++)
            {
                if((int)tablemodel.getValueAt(i, 0) == productSupplier.getProductSupplierId())
                {
                    JOptionPane.showMessageDialog(null, "This package is already linked to this product and supplier.");
                    canAdd = false;
                    break;
                }             
                canAdd = true;             
            }
            if(canAdd)
            {
                tablemodel.addRow(new Object[]{productSupplier.getProductSupplierId(), prodName, suppName});
            }     
        }
    }//GEN-LAST:event_btmAddProductSupplierActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAddProductSupplier;
    private javax.swing.JButton btnRemoveProductSupplier;
    private javax.swing.JComboBox cmbProducts;
    private javax.swing.JComboBox cmbSuppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
