/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workshop6.GUI;

import java.beans.PropertyVetoException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import workshop6.DBClasses.PackageDB;
import workshop6.DBClasses.ProductDB;
import workshop6.DBClasses.SupplierDB;
import workshop6.Entity.Product;
import workshop6.Entity.Supplier;

/**
 *
 * 
 */
public class PackageMainFrame extends javax.swing.JInternalFrame {

    public workshop6.Entity.Package pkg;
    public workshop6.Entity.Package modPkg;
    private static ComboBoxModel cbPackageIdModel;
    
    /**
     * Creates new form PackageMainFrame
     */
    public PackageMainFrame() {
        initComponents();
        UpdatePackagesList();
        this.setTitle("Package Maintenance");
    }

    
    public static void UpdatePackagesList()
    {
        cbPackageIdModel = new DefaultComboBoxModel(PackageDB.getPackageIDs());
        cmbPackageId.setModel(cbPackageIdModel);
        cmbPackageId.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbPackageId = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtPkgName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPkgDescription = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPkgStartDate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPkgEndDate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPkgBasePrice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPkgAgencyCommission = new javax.swing.JTextField();
        btnAddPackages = new javax.swing.JButton();
        btnEditPackages = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProducts = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSuppliers = new javax.swing.JList();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Package ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        cmbPackageId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPackageIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jPanel1.add(cmbPackageId, gridBagConstraints);

        jLabel11.setText("Package Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 10);
        jPanel1.add(jLabel11, gridBagConstraints);

        txtPkgName.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jPanel1.add(txtPkgName, gridBagConstraints);

        jLabel17.setText("Package Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 10);
        jPanel1.add(jLabel17, gridBagConstraints);

        txtPkgDescription.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jPanel1.add(txtPkgDescription, gridBagConstraints);

        jLabel13.setText("Package Start Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 10);
        jPanel1.add(jLabel13, gridBagConstraints);

        txtPkgStartDate.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jPanel1.add(txtPkgStartDate, gridBagConstraints);

        jLabel15.setText("Package End Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 10);
        jPanel1.add(jLabel15, gridBagConstraints);

        txtPkgEndDate.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jPanel1.add(txtPkgEndDate, gridBagConstraints);

        jLabel12.setText("Package Base Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 10);
        jPanel1.add(jLabel12, gridBagConstraints);

        txtPkgBasePrice.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jPanel1.add(txtPkgBasePrice, gridBagConstraints);

        jLabel16.setText("Package Agency Commission");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 10);
        jPanel1.add(jLabel16, gridBagConstraints);

        txtPkgAgencyCommission.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        jPanel1.add(txtPkgAgencyCommission, gridBagConstraints);

        btnAddPackages.setText("Add");
        btnAddPackages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPackagesActionPerformed(evt);
            }
        });

        btnEditPackages.setText("Edit");
        btnEditPackages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPackagesActionPerformed(evt);
            }
        });

        jLabel3.setText("Related Products:");

        jLabel1.setText("Related Suppliers:");

        jScrollPane1.setViewportView(listProducts);

        jScrollPane2.setViewportView(listSuppliers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnAddPackages)
                        .addGap(179, 179, 179)
                        .addComponent(btnEditPackages)))
                .addGap(52, 82, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPackages)
                    .addComponent(btnEditPackages))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPackageIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPackageIdActionPerformed
        String packageId = (String) cmbPackageId.getSelectedItem();
        pkg = PackageDB.getPackage(packageId);
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        NumberFormat currency = NumberFormat.getCurrencyInstance();
        currency.setMinimumFractionDigits(2);
        txtPkgName.setText(pkg.getPkgName());
        txtPkgDescription.setText(pkg.getPkgDesc());
        txtPkgStartDate.setText(df.format(pkg.getPkgStartDate()));
        txtPkgEndDate.setText(df.format(pkg.getPkgEndDate()));
        txtPkgBasePrice.setText(currency.format(pkg.getPkgBasePrice()));
        txtPkgAgencyCommission.setText(currency.format(pkg.getPkgAgencyCommission()));

        //Adam - Populate the list of products and suppliers

        List<Product> products = ProductDB.getProductsForPackageId(pkg.getPackageId());

        DefaultListModel productListModel = new DefaultListModel();
        listProducts.setModel(productListModel);

        for(Product prod : products)
        {
            productListModel.addElement(prod.getProdName());
        }

        List<Supplier> suppliers = SupplierDB.getSuppliersForPackageId(pkg.getPackageId());

        DefaultListModel supplierListModel = new DefaultListModel();
        listSuppliers.setModel(supplierListModel);

        for(Supplier supp : suppliers)
        {
            supplierListModel.addElement(supp.getSupName());
        }
    }//GEN-LAST:event_cmbPackageIdActionPerformed

    private void btnAddPackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPackagesActionPerformed
         if(!Main.checkIfFrameAlreadyOpen(AddEditPackagesFrame.class))
        { 
            AddEditPackagesFrame addEditPackage = new AddEditPackagesFrame(this, true, null);
            getDesktopPane().add(addEditPackage);
            addEditPackage.setVisible(true);
            try {
                addEditPackage.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PackageMainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "You are currently "+ ((AddEditPackagesFrame.addPackages == false) ? "editing" : "adding") +" a package. Please close this window in order to open a new editor.");
        }
    }//GEN-LAST:event_btnAddPackagesActionPerformed

    private void btnEditPackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPackagesActionPerformed
        if(!Main.checkIfFrameAlreadyOpen(AddEditPackagesFrame.class))
        { 
            AddEditPackagesFrame addEditPackage = new AddEditPackagesFrame(this, false, pkg);
            addEditPackage.displayPackage(pkg);
            getDesktopPane().add(addEditPackage);
            addEditPackage.setVisible(true);
            try {
                addEditPackage.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(PackageMainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "You are currently "+ ((AddEditPackagesFrame.addPackages == false) ? "editing" : "adding") +" a package. Please close this window in order to open a new editor.");
        }
    }//GEN-LAST:event_btnEditPackagesActionPerformed

     //Method to retrieve package details from Add or Edit package frame
    public void postData(workshop6.Entity.Package modPkg)
    {    
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //this.cmbPackageId.setSelectedIndex(modPkg.getPackageId());
        this.txtPkgName.setText(modPkg.getPkgName());
        this.txtPkgDescription.setText(modPkg.getPkgDesc());
        this.txtPkgStartDate.setText(sdf.format(modPkg.getPkgStartDate()));
        this.txtPkgEndDate.setText(sdf.format(modPkg.getPkgEndDate()));
        this.txtPkgAgencyCommission.setText(Double.toString(modPkg.getPkgAgencyCommission()));
        this.txtPkgBasePrice.setText(Double.toString(modPkg.getPkgBasePrice()));      
        //cmbPackageId.removeAllItems();
        //initPackageIdCombo(cmbPackageId);
        pkg = modPkg;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPackages;
    private javax.swing.JButton btnEditPackages;
    private static javax.swing.JComboBox cmbPackageId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listProducts;
    private javax.swing.JList listSuppliers;
    private javax.swing.JTextField txtPkgAgencyCommission;
    private javax.swing.JTextField txtPkgBasePrice;
    private javax.swing.JTextField txtPkgDescription;
    private javax.swing.JTextField txtPkgEndDate;
    private javax.swing.JTextField txtPkgName;
    private javax.swing.JTextField txtPkgStartDate;
    // End of variables declaration//GEN-END:variables
}
