/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workshop6.GUI;

import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import workshop6.DBClasses.AgentDB;
import workshop6.DBClasses.CustomerDB;
import workshop6.Entity.Agent;
import workshop6.Entity.Customer;

/**
 *
 * @author Darya O
 */
public class ReassignCustomersForm extends javax.swing.JInternalFrame {

     private Vector<Customer> customers;
    private Vector<Agent> agents;
    private int agent;
    private int cust;
    private int agentId;
    
    
    /**
     * Creates new form ReassignCustomersForm
     */
    public ReassignCustomersForm(int agentID) {
        initComponents();
        agentId = agentID;
        updateCustomerList(agentId);
        updateAgentComboBox();
        this.setTitle("Editing customers that are assigned to Agent id: " + agentID);
        lblCurrentlyEditing.setText("Editing customers for AgentID: " + agentID);
    }

     private void updateAgentComboBox() {
        //populate the combo box
        agents = AgentDB.GetAllAgents();
        for(Agent a : agents)
            cbAgents.addItem(a.getAgtLastName() + ", " + a.getAgtFirstName()
                    + " (Agent ID: " + a.getAgentId() + ")");
    }
     
      private void updateCustomerList(int agentId) {
        //populate the iist of customers
        customers = CustomerDB.GetCustomersByAgentId(agentId);
        DefaultListModel<String> model = new DefaultListModel<>();
        for(Customer c : customers)
            model.addElement(c.getCustFirstName() + " " + c.getCustLastName()
                    + " (Customer ID: " + c.getCustomerId() + ")");
        lsCustomers.setModel(model);
        lsCustomers.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsCustomers = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        cbAgents = new javax.swing.JComboBox();
        btnCancel = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        lblCurrentlyEditing = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Customer(s) to reassign:");

        lsCustomers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lsCustomers);

        jLabel2.setText("Pick new agent:");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        lblCurrentlyEditing.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCurrentlyEditing, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 196, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(cbAgents, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAccept)
                            .addComponent(btnCancel))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentlyEditing)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAgents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccept))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed

        int i = cbAgents.getSelectedIndex();
        Agent a = agents.get(i);

        int[] indices = lsCustomers.getSelectedIndices();
        boolean isChangeSuccessful = false;

        for(int ind : indices)
        {
            Customer selectedCustomer = customers.get(ind);
            Agent selectedAgent = agents.get(i);
            isChangeSuccessful = CustomerDB.UpdateCustomerAgentId(selectedCustomer.getCustomerId(), selectedAgent.getAgentId());
        }

        if(isChangeSuccessful){
            JOptionPane.showConfirmDialog(null, "Successful change", "Customer reassigned", JOptionPane.PLAIN_MESSAGE);
            updateCustomerList(agentId);

        }
    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox cbAgents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentlyEditing;
    private javax.swing.JList lsCustomers;
    // End of variables declaration//GEN-END:variables
}
